### ISSUE TITLE
Bugs with selectors and multiple elements

### ISSUE THREAD

**Issue by wesbos** [typicode/mistcss#72]
Great lib! A few issues and suggestions, all revolving around some valid CSS selectors. 

First, I'd like to be able to specify something like this and have it available to all elements:

```css
[data-card-variant="primary"] {
  background-color: green;
  color: white;
}
```

On it's own it generates nothing.

When there is a selector above it, it merges it:

```css
button {
  border-radius: 1rem;
  &[data-variant="primary"] {
    color: white;
  }
}

[data-card-variant="primary"] {
  background-color: green;
  color: white;
}
```

Sticks them all on button:

```ts
interface Mist_button extends ReactHTMLProps<'button'> {
  'data-variant'?: 'primary'
  'data-card-variant'?: 'primary'
}
```

I tried a few different ways to select multiple elements.

Nothing is generated for for this:

```css
[data-card-variant="primary"]:is(div, article, section) {
  color: white;
}
```

This one generates the interfaces for all elements, but only applies it to the last one:

```css
*:is(div, article, section)[data-card-variant="primary"] {
  color: white;
}
```

```ts
interface Mist_div extends ReactHTMLProps<'div'> {
}

interface Mist_article extends ReactHTMLProps<'article'> {
}

interface Mist_section extends ReactHTMLProps<'section'> {
  'data-card-variant'?: 'primary'
}
```

As does this:

```css
article,
div,
section {
  &[data-card-variant="primary"] {
    color: white;
  }
}
```

I did get this to work, but it's not very scalable:

```css
div[data-card-variant="primary"],
article[data-card-variant="primary"],
section[data-card-variant="primary"] {
  color: white;
}
```
